
@startuml main_sequence
title MAIN FUNCTION FLOW
autonumber
hide footbox

activate Main
Main -> BMSAdapter : BMSAdapter()
activate BMSAdapter
BMSAdapter -> BMSTree : BMSTree(BMSDecryptor&)
activate BMSTree
BMSAdapter -> BMSDecryptor : BMSDecryptor(BMSData&)
activate BMSDecryptor
BMSAdapter -> BMSTree : Load()
BMSTree -> BMSTree : SearchDir
alt Exist Cache?
    BMSTree -> BMSTree : AddMusic(path, vec)
end
BMSTree -> BMSTree : SetMusicList()
loop Exist new Music or Pattern
    |||
    BMSTree -> BMSDecryptor : BuildInfoData(path)
    |||
end
Main -> Main : Select Folder, Music, Pattern
Main -> BMSAdapter : Play(BMSInfoData&)

loop Until input Esc key
    |||
    alt input Esc
        |||
        Main -> BMSAdapter : TerminateMusic()
        |||
    else input left or right arrow
        |||
        Main -> BMSAdapter : TerminateMusic()
        Main -> Main : Change Folder Index
        Main -> BMSAdapter : Play(BMSInfoData&)
        |||
    else input up or down arrow
        |||
        Main -> BMSAdapter : TerminateMusic()
        Main -> Main : Change Music Index
        Main -> BMSAdapter : Play(BMSInfoData&)
        |||
    else input `[` or `]` key
        |||
        Main -> BMSAdapter : TerminateMusic()
        Main -> Main : Change Pattern Index
        Main -> BMSAdapter : Play(BMSInfoData&)
        |||
    end
    |||
end
@enduml